version: '3.8'

services:
  jupyter:
    # Official NVIDIA PyTorch container with JupyterLab
    # CUDA 12.4 + Python 3.10 + PyTorch 2.4 + JupyterLab pre-installed
    image: nvcr.io/nvidia/pytorch:24.07-py3
    ports:
      - "8888:8888"
    volumes:
      - workspace_data:/workspace
    command: >
      bash -c "
      pip install jupyterlab ipywidgets &&
      test -f /workspace/hello_world.ipynb || curl -o /workspace/hello_world.ipynb https://raw.githubusercontent.com/nvidia-beer/hello-world-launchable/main/hello_world.ipynb &&
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root 
      --NotebookApp.token='' --NotebookApp.password=''"
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  workspace_data:
    driver: local

