version: '3.8'

services:
  jupyter:
    # Pre-built image from Docker Hub (build and push your Dockerfile first)
    # Replace with your Docker Hub username: YOUR-USERNAME/hello-world-launchable:latest
    image: nvidiaibeer/hello-world-launchable:latest
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

