# Brev Configuration
name: hello-world-launchable
description: A simple GPU test launchable with CUDA and Jupyter

# Container configuration
container:
  compose_file: ./docker-compose.yml
  
# Port forwarding for Jupyter
ports:
  - 8888:8888

# Resource requirements
resources:
  gpu: true
  gpu_count: 1
  gpu_type: L40S  # or "l40s" or "NVIDIA-L40S" - depends on Brev's syntax
  memory: 48GB  # or higher to support the GPU workload
